name: Announcements-OG
author: freetolga
description: regular announcments based on utilities-og
website: https://github.com/true-og/Announcements-OG
version: '${version}'
api-version: '${apiVersion}'
main: plugin.AnnouncementsOG
depend: 
  - Utilities-OG
